# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fluorburst_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import (
    QApplication, QDialog, QMainWindow, QMessageBox, QPushButton, QVBoxLayout
)

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
import matplotlib.pyplot as plt

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1006, 756)
        Main.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.label = QtWidgets.QLabel(Main)
        self.label.setGeometry(QtCore.QRect(10, 20, 175, 33))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.b_load_xtc_pdb = QtWidgets.QPushButton(Main)
        self.b_load_xtc_pdb.setGeometry(QtCore.QRect(210, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.b_load_xtc_pdb.setFont(font)
        self.b_load_xtc_pdb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_load_xtc_pdb.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: \'#ffffff\';\n"
"    border-radius: 6px;\n"
"    border: 2px solid \'#000000\';\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: \'#ffe278\';\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.b_load_xtc_pdb.setObjectName("b_load_xtc_pdb")
        self.label_20 = QtWidgets.QLabel(Main)
        self.label_20.setGeometry(QtCore.QRect(10, 71, 137, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setObjectName("label_20")
        self.comboBox_2 = QtWidgets.QComboBox(Main)
        self.comboBox_2.setGeometry(QtCore.QRect(178, 71, 141, 22))
        self.comboBox_2.setStyleSheet("")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setCurrentText("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.b_load_experiment = QtWidgets.QPushButton(Main)
        self.b_load_experiment.setGeometry(QtCore.QRect(347, 67, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.b_load_experiment.setFont(font)
        self.b_load_experiment.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_load_experiment.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: \'#ffffff\';\n"
"    border-radius: 6px;\n"
"    border: 2px solid \'#000000\';\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: \'#ffe278\';\n"
"}\n"
"")
        self.b_load_experiment.setObjectName("b_load_experiment")
        self.label_2 = QtWidgets.QLabel(Main)
        self.label_2.setGeometry(QtCore.QRect(10, 107, 62, 32))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(Main)
        self.label_7.setGeometry(QtCore.QRect(200, 107, 61, 32))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(Main)
        self.label_16.setGeometry(QtCore.QRect(476, 107, 79, 32))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(Main)
        self.label_19.setGeometry(QtCore.QRect(715, 107, 114, 32))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setObjectName("label_19")
        self.label_3 = QtWidgets.QLabel(Main)
        self.label_3.setGeometry(QtCore.QRect(10, 156, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.i_taud = QtWidgets.QLineEdit(Main)
        self.i_taud.setGeometry(QtCore.QRect(57, 156, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_taud.setFont(font)
        self.i_taud.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"\n"
"\n"
"")
        self.i_taud.setObjectName("i_taud")
        self.label_10 = QtWidgets.QLabel(Main)
        self.label_10.setGeometry(QtCore.QRect(200, 156, 105, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setObjectName("label_10")
        self.I_r0 = QtWidgets.QLineEdit(Main)
        self.I_r0.setGeometry(QtCore.QRect(333, 156, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.I_r0.setFont(font)
        self.I_r0.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.I_r0.setObjectName("I_r0")
        self.label_14 = QtWidgets.QLabel(Main)
        self.label_14.setGeometry(QtCore.QRect(476, 156, 83, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setObjectName("label_14")
        self.i_llimit = QtWidgets.QLineEdit(Main)
        self.i_llimit.setGeometry(QtCore.QRect(572, 156, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_llimit.setFont(font)
        self.i_llimit.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.i_llimit.setObjectName("i_llimit")
        self.label_22 = QtWidgets.QLabel(Main)
        self.label_22.setGeometry(QtCore.QRect(715, 156, 53, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setTextFormat(QtCore.Qt.AutoText)
        self.label_22.setObjectName("label_22")
        self.i_bursts = QtWidgets.QLineEdit(Main)
        self.i_bursts.setGeometry(QtCore.QRect(852, 156, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_bursts.setFont(font)
        self.i_bursts.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.i_bursts.setObjectName("i_bursts")
        self.label_4 = QtWidgets.QLabel(Main)
        self.label_4.setGeometry(QtCore.QRect(10, 184, 39, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.i_tauA = QtWidgets.QLineEdit(Main)
        self.i_tauA.setGeometry(QtCore.QRect(57, 184, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_tauA.setFont(font)
        self.i_tauA.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.i_tauA.setObjectName("i_tauA")
        self.label_11 = QtWidgets.QLabel(Main)
        self.label_11.setGeometry(QtCore.QRect(200, 184, 18, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName("label_11")
        self.i_kappa = QtWidgets.QLineEdit(Main)
        self.i_kappa.setGeometry(QtCore.QRect(333, 184, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_kappa.setFont(font)
        self.i_kappa.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.i_kappa.setObjectName("i_kappa")
        self.label_15 = QtWidgets.QLabel(Main)
        self.label_15.setGeometry(QtCore.QRect(476, 184, 87, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setObjectName("label_15")
        self.i_ulimit = QtWidgets.QLineEdit(Main)
        self.i_ulimit.setGeometry(QtCore.QRect(572, 184, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_ulimit.setFont(font)
        self.i_ulimit.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.i_ulimit.setObjectName("i_ulimit")
        self.label_21 = QtWidgets.QLabel(Main)
        self.label_21.setGeometry(QtCore.QRect(715, 184, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setObjectName("label_21")
        self.i_sfstart = QtWidgets.QLineEdit(Main)
        self.i_sfstart.setGeometry(QtCore.QRect(852, 184, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_sfstart.setFont(font)
        self.i_sfstart.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.i_sfstart.setObjectName("i_sfstart")
        self.label_5 = QtWidgets.QLabel(Main)
        self.label_5.setGeometry(QtCore.QRect(10, 212, 28, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.i_qd = QtWidgets.QLineEdit(Main)
        self.i_qd.setGeometry(QtCore.QRect(57, 212, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_qd.setFont(font)
        self.i_qd.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.i_qd.setObjectName("i_qd")
        self.label_9 = QtWidgets.QLabel(Main)
        self.label_9.setGeometry(QtCore.QRect(200, 212, 127, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setObjectName("label_9")
        self.i_quench = QtWidgets.QLineEdit(Main)
        self.i_quench.setGeometry(QtCore.QRect(333, 212, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_quench.setFont(font)
        self.i_quench.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.i_quench.setObjectName("i_quench")
        self.label_13 = QtWidgets.QLabel(Main)
        self.label_13.setGeometry(QtCore.QRect(476, 212, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setObjectName("label_13")
        self.i_lambda = QtWidgets.QLineEdit(Main)
        self.i_lambda.setGeometry(QtCore.QRect(572, 212, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_lambda.setFont(font)
        self.i_lambda.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.i_lambda.setObjectName("i_lambda")
        self.label_18 = QtWidgets.QLabel(Main)
        self.label_18.setGeometry(QtCore.QRect(715, 212, 124, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setTextFormat(QtCore.Qt.AutoText)
        self.label_18.setObjectName("label_18")
        self.i_sfend = QtWidgets.QLineEdit(Main)
        self.i_sfend.setGeometry(QtCore.QRect(852, 212, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_sfend.setFont(font)
        self.i_sfend.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.i_sfend.setObjectName("i_sfend")
        self.label_6 = QtWidgets.QLabel(Main)
        self.label_6.setGeometry(QtCore.QRect(10, 240, 26, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.i_qa = QtWidgets.QLineEdit(Main)
        self.i_qa.setGeometry(QtCore.QRect(57, 242, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.i_qa.setFont(font)
        self.i_qa.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"")
        self.i_qa.setObjectName("i_qa")
        self.r_gamma = QtWidgets.QRadioButton(Main)
        self.r_gamma.setGeometry(QtCore.QRect(200, 240, 163, 26))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.r_gamma.setFont(font)
        self.r_gamma.setAutoFillBackground(False)
        self.r_gamma.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  13px;\n"
"    height:                 13px;\n"
"    border-radius:         8px;\n"
"    border-collapse: separate;\n"
"    border-spacing: 1px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:        \'#ffe278\';\n"
"    border:                 2px solid black;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       white;\n"
"    border:                 2px solid black;\n"
"}")
        self.r_gamma.setChecked(True)
        self.r_gamma.setObjectName("r_gamma")
        self.b_calculate = QtWidgets.QPushButton(Main)
        self.b_calculate.setGeometry(QtCore.QRect(476, 241, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.b_calculate.setFont(font)
        self.b_calculate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_calculate.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: \'#ffffff\';\n"
"    border-radius: 6px;\n"
"    border: 2px solid \'#000000\';\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: \'#ffe278\';\n"
"}\n"
"")
        self.b_calculate.setObjectName("b_calculate")
        self.b_import_params = QtWidgets.QPushButton(Main)
        self.b_import_params.setGeometry(QtCore.QRect(720, 240, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.b_import_params.setFont(font)
        self.b_import_params.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_import_params.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: \'#ffffff\';\n"
"    border-radius: 6px;\n"
"    border: 2px solid \'#000000\';\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: \'#ffe278\';\n"
"}\n"
"")
        self.b_import_params.setObjectName("b_import_params")
        self.b_exprot_params = QtWidgets.QPushButton(Main)
        self.b_exprot_params.setGeometry(QtCore.QRect(850, 240, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.b_exprot_params.setFont(font)
        self.b_exprot_params.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_exprot_params.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: \'#ffffff\';\n"
"    border-radius: 6px;\n"
"    border: 2px solid \'#000000\';\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: \'#ffe278\';\n"
"}\n"
"")
        self.b_exprot_params.setObjectName("b_exprot_params")
        self.line = QtWidgets.QFrame(Main)
        self.line.setGeometry(QtCore.QRect(9, 290, 988, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_12 = QtWidgets.QLabel(Main)
        self.label_12.setGeometry(QtCore.QRect(9, 416, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setObjectName("label_12")
        self.comboBox = QtWidgets.QComboBox(Main)
        self.comboBox.setGeometry(QtCore.QRect(9, 444, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label_17 = QtWidgets.QLabel(Main)
        self.label_17.setGeometry(QtCore.QRect(9, 566, 36, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setObjectName("label_17")
        self.bins = QtWidgets.QLineEdit(Main)
        self.bins.setGeometry(QtCore.QRect(56, 566, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.bins.setFont(font)
        self.bins.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    border: 2px solid  rgb(208, 208, 208);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"    border: 3px solid rgb(158, 158, 158);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(200, 177, 0)\n"
"}\n"
"\n"
"\n"
"")
        self.bins.setObjectName("bins")
        self.ffvis = QtWidgets.QWidget(Main)
        self.ffvis.setGeometry(QtCore.QRect(285, 348, 561, 371))
        self.ffvis.setStyleSheet("QWidget{\n"
"\n"
"    border: 2px solid black;\n"
"    border-radius: 15px\n"
"}")
        self.ffvis.setObjectName("ffvis")
        self.b_FRET = QtWidgets.QPushButton(Main)
        self.b_FRET.setGeometry(QtCore.QRect(305, 320, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b_FRET.setFont(font)
        self.b_FRET.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: \'#ffffff\';\n"
"    border-top-left-radius: 6px;\n"
"    border-left: 2px solid \'#000000\';\n"
"    border-right: 2px solid \'#000000\';\n"
"    border-top: 2px solid \'#000000\';\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: \'#ffe278\';\n"
"}\n"
"\n"
"")
        self.b_FRET.setObjectName("b_FRET")
        self.b_kappa2 = QtWidgets.QPushButton(Main)
        self.b_kappa2.setGeometry(QtCore.QRect(380, 320, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b_kappa2.setFont(font)
        self.b_kappa2.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: \'#ffffff\';\n"
"    border-right: 2px solid \'#000000\';\n"
"    border-top: 2px solid \'#000000\';\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: \'#ffe278\';\n"
"}\n"
"\n"
"")
        self.b_kappa2.setObjectName("b_kappa2")
        self.b_rda = QtWidgets.QPushButton(Main)
        self.b_rda.setGeometry(QtCore.QRect(455, 320, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b_rda.setFont(font)
        self.b_rda.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: \'#ffffff\';\n"
"    border-right: 2px solid \'#000000\';\n"
"    border-top: 2px solid \'#000000\';\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: \'#ffe278\';\n"
"}\n"
"")
        self.b_rda.setObjectName("b_rda")
        self.r_ap = QtWidgets.QPushButton(Main)
        self.r_ap.setGeometry(QtCore.QRect(530, 320, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.r_ap.setFont(font)
        self.r_ap.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: \'#ffffff\';\n"
"    border-top-right-radius: 6px;\n"
"    border-right: 2px solid \'#000000\';\n"
"    border-top: 2px solid \'#000000\';\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: \'#ffe278\';\n"
"}\n"
"")
        self.r_ap.setObjectName("r_ap")

        # a figure instance to plot on
        self.figure = plt.figure()

        # this is the Canvas Widget that displays the `figure`
        # it takes the `figure` instance as a parameter to __init__
        self.canvas = FigureCanvas(self.figure)

        # this is the Navigation widget
        # it takes the Canvas widget and a parent
        self.toolbar = NavigationToolbar(self.canvas, self)

        # Just some button connected to `plot` method
        self.button = QPushButton('Plot')
        # set the layout
        layout = QVBoxLayout()
        layout.addWidget(self.toolbar)
        layout.addWidget(self.canvas)
        self.ffvis.setLayout(layout)

        self.retranslateUi(Main)
        self.comboBox_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Fluorburst"))
        self.label.setText(_translate("Main", "Fluorburst GUI"))
        self.b_load_xtc_pdb.setText(_translate("Main", "Add MD run"))
        self.label_20.setText(_translate("Main", "Calculate Burts of:"))
        self.b_load_experiment.setText(_translate("Main", "add experimental Data"))
        self.label_2.setText(_translate("Main", "Dyes:"))
        self.label_7.setText(_translate("Main", "FRET:"))
        self.label_16.setText(_translate("Main", "Bursts:"))
        self.label_19.setText(_translate("Main", "Sampling:"))
        self.label_3.setText(_translate("Main", "tauD:"))
        self.i_taud.setText(_translate("Main", "1.4"))
        self.label_10.setText(_translate("Main", "R0 (Angstöm):"))
        self.I_r0.setText(_translate("Main", "5.4"))
        self.label_14.setText(_translate("Main", "lower limit:"))
        self.i_llimit.setText(_translate("Main", "40"))
        self.label_22.setText(_translate("Main", "bursts:"))
        self.i_bursts.setText(_translate("Main", "1000"))
        self.label_4.setText(_translate("Main", "tauA:"))
        self.i_tauA.setText(_translate("Main", "1.0"))
        self.label_11.setText(_translate("Main", "𝜅2"))
        self.i_kappa.setText(_translate("Main", "0.6666"))
        self.label_15.setText(_translate("Main", "upper limit:"))
        self.i_ulimit.setText(_translate("Main", "120"))
        self.label_21.setText(_translate("Main", "skip frames start:"))
        self.i_sfstart.setText(_translate("Main", "0"))
        self.label_5.setText(_translate("Main", "QD:"))
        self.i_qd.setText(_translate("Main", "0.2"))
        self.label_9.setText(_translate("Main", "quenchin radius:"))
        self.i_quench.setText(_translate("Main", "1.0"))
        self.label_13.setText(_translate("Main", "lambda:"))
        self.i_lambda.setText(_translate("Main", "-2.3"))
        self.label_18.setText(_translate("Main", "skip frames end:"))
        self.i_sfend.setText(_translate("Main", "0"))
        self.label_6.setText(_translate("Main", "QA:"))
        self.i_qa.setText(_translate("Main", "0.3"))
        self.r_gamma.setText(_translate("Main", "gamma correction"))
        self.b_calculate.setText(_translate("Main", "Calculate Bursts"))
        self.b_import_params.setText(_translate("Main", "import params"))
        self.b_exprot_params.setText(_translate("Main", "export params"))
        self.label_12.setText(_translate("Main", "Plot data of:"))
        self.label_17.setText(_translate("Main", "bins:"))
        self.bins.setText(_translate("Main", "30"))
        self.b_FRET.setText(_translate("Main", "FRET"))
        self.b_kappa2.setText(_translate("Main", "kappa"))
        self.b_rda.setText(_translate("Main", "RDA"))
        self.r_ap.setText(_translate("Main", "RAP"))
